name: Condition and Expression Demo

on:
  workflow_dispatch:
    inputs:
      failstep:
        description: 'Fail step in Job1 (yes/no)'
        required: true
        default: 'no'

jobs:
  first-job:

    runs-on: ubuntu-latest
    
    steps:
    
      - name: checkout code if running on master branch
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/checkout@v2
        
      - name: YES was passed as workflow input
        if: github.event.inputs.failstep == 'yes'
        run: echo "Value passed by workflow_dispatch is YES to fail workflow." 

      - name: NO was passed as workflow input
        run: echo "Value passed by workflow_dispatch is NO to fail workflow." 
        if: github.event.inputs.failstep == 'no'
      
      - name: Step that can be failed
        env:
          FAIL_STEP: ${{ github.event.inputs.failstep == 'yes' }}
        run:  |
          echo "This statement runs whether step exits 0 or 1"
          if [[ $FAIL_STEP == true ]]
          then
            exit 1
          fi

      - name: Step in workflow
        run: echo "Another step in the workflow" 

      - name: This step only runs if there's a previous failure
        if: failure()
        run: echo "There has been a failure.  Perhaps send a notification." 

      - name: Step in workflow
        run: echo "Another step in the workflow" 
          
      - name: Step that always runs
        if: always()
        run:  echo "This step runs regardless of success or failure." 
          
      - name: Step that only runs on success of all steps
        if: success()
        run:  echo "This step only runs when no previous steps have failed." 

  second-job:
  
    runs-on: ubuntu-latest
    
    needs: first-job
    if: always()
    steps:
      - name: Sample step in job
        run:  echo "Sample step output" 
